return {
    [1] = { name = "First Step Forward +", goal = 1 },
    [2] = { name = "Vanquish 1 Enemy +", goal = 1 },
    [3] = { name = "Undertake a FoV Training Regime", goal = 1 },
    [4] = { name = "Heal without magic", goal = 1 },
    [5] = { name = "All for One", goal = 1 },
    [11] = { name = "Undertake a GoV Training Regime", goal = 1 },
    [12] = { name = "Vanquish Multiple Enemies I - 200", goal = 200 },
    [13] = { name = "Vanquish Multiple Enemies II - 500", goal = 500 },
    [14] = { name = "Vanquish Multiple Enemies III - 750", goal = 750 },
    [15] = { name = "Level Sync to Vanquish I", goal = 200 },
    [16] = { name = "Deal 500+ Damage", goal = 200 },
    [17] = { name = "Deal 1000+ Damage", goal = 150 },
    [18] = { name = "Deal 1500+ Damage", goal = 100 },
    [19] = { name = "Deal 10-20 Damage", goal = 10 },
    [20] = { name = "Deal 110-120 Damage", goal = 10 },
    [21] = { name = "Deal 310-320 Damage", goal = 10 },
    [22] = { name = "Deal 510-520 Damage", goal = 10 },
    [23] = { name = "Deal 1110-1120 Damage", goal = 10 },
    [29] = { name = "Total Damage I", goal = 100000 },
    [30] = { name = "Total Damage II", goal = 200000 },
    [31] = { name = "Total Healing I", goal = 10000 },
    [32] = { name = "Total Healing II", goal = 20000 },
    [33] = { name = "Total Damage Taken I", goal = 10000 },
    [34] = { name = "Total Damage Taken II", goal = 20000 },
    [45] = { name = "Weapon Skills 1", goal = 100 },
    [57] = { name = "Total Successful Synthesis Attempts", goal = 30 },
    [63] = { name = "Total Suc. Chocobo Digs", goal = 30 },
    [65] = { name = "Mons.: Total Monsters Vanquished", goal = 100 },
    [71] = { name = "Spoils - Fire Crystals", goal = 10 },
    [72] = { name = "Spoils - Ice Crystals", goal = 10 },
    [73] = { name = "Spoils - Wind Crystals", goal = 10 },
    [74] = { name = "Spoils - Earth Crystals", goal = 10 },
    [75] = { name = "Spoils - Lightning Crystals", goal = 10 },
    [76] = { name = "Spoils - Water Crystals", goal = 10 },
    [77] = { name = "Spoils - Light Crystals", goal = 10 },
    [78] = { name = "Spoils - Dark Crystals", goal = 10 },
    [84] = { name = "Spoils - Flame Geode", goal = 3 },
    [85] = { name = "Spoils - Snow Geode", goal = 3 },
    [86] = { name = "Spoils - Breeze Geode", goal = 3 },
    [87] = { name = "Spoils - Soil Geode", goal = 3 },
    [88] = { name = "Spoils - Thunder Geode", goal = 3 },
    [89] = { name = "Spoils - Aqua Geode", goal = 3 },
    [90] = { name = "Spoils - Light Geode", goal = 3 },
    [91] = { name = "Spoils - Shadow Geode", goal = 3 },
    [92] = { name = "Spoils - Ifritite", goal = 3 },
    [93] = { name = "Spoils - Shivite", goal = 3 },
    [94] = { name = "Spoils - Garudite", goal = 3 },
    [95] = { name = "Spoils - Titanite", goal = 3 },
    [96] = { name = "Spoils - Ramuite", goal = 3 },
    [97] = { name = "Spoils - Leviatite", goal = 3 },
    [98] = { name = "Spoils - Carbite", goal = 3 },
    [99] = { name = "Spoils - Fenrite", goal = 3 },
    [100] = { name = "Speak to Carpenters\' Guild Master", goal = 1 },
    [101] = { name = "Speak to Blacksmiths\' Guild Master", goal = 1 },
    [102] = { name = "Speak to Goldsmiths\' Guild Master", goal = 1 },
    [103] = { name = "Speak to Weavers\' Guild Master", goal = 1 },
    [104] = { name = "Speak to Tanners\' Guild Master", goal = 1 },
    [105] = { name = "Speak to Boneworkers\' Guild Master", goal = 1 },
    [106] = { name = "Speak to Alchemists\' Guild Master", goal = 1 },
    [107] = { name = "Speak to Culinarians\' Guild Master", goal = 1 },
    [108] = { name = "Woodworking: Padded Box", goal = 1 },
    [109] = { name = "Smithing: Bronze Knife", goal = 1 },
    [110] = { name = "Goldsmithing: Copper Ring", goal = 1 },
    [111] = { name = "Weaving: Headgear", goal = 1 },
    [112] = { name = "Tanning: Leather Bandana", goal = 1 },
    [113] = { name = "Boneworking: Shell Powder", goal = 1 },
    [114] = { name = "Alchemy: Black Ink", goal = 1 },
    [115] = { name = "Cooking: Pebble Soup", goal = 1 },
    [117] = { name = "Level Sync to Vanquish II", goal = 20 },
    [120] = { name = "Spoils - Bat Wing", goal = 2 },
    [121] = { name = "Spoils - Black Tiger Fang", goal = 2 },
    [122] = { name = "Spoils - Flint Stone", goal = 2 },
    [123] = { name = "Spoils - Rabbit Hide", goal = 2 },
    [124] = { name = "Spoils - Honey", goal = 2 },
    [125] = { name = "Spoils - Sheepskin", goal = 2 },
    [126] = { name = "Spoils - Lizard Skin", goal = 2 },
    [127] = { name = "Spoils - Beetle Shell", goal = 2 },
    [128] = { name = "Spoils - Zeruhn Soot", goal = 2 },
    [129] = { name = "Spoils - Silver Name Tag", goal = 1 },
    [130] = { name = "Spoils - Quadav Helm", goal = 2 },
    [132] = { name = "Spoils - Treant Bulb", goal = 2 },
    [133] = { name = "Spoils - Wild Onion", goal = 2 },
    [134] = { name = "Spoils - Sleepshroom", goal = 2 },
    [135] = { name = "Spoils - Sand Bat Fang", goal = 2 },
    [136] = { name = "Spoils - Zinc Ore", goal = 2 },
    [137] = { name = "Spoils - Giant Bird Feather", goal = 2 },
    [138] = { name = "Spoils - Three-leaf Mandragora Bud", goal = 1 },
    [139] = { name = "Spoils - Four-leaf Mandragora Bud", goal = 1 },
    [140] = { name = "Spoils - Cornette", goal = 2 },
    [141] = { name = "Spoils - Yuhtunga Sulfur", goal = 1 },
    [142] = { name = "Spoils - Snobby Letter", goal = 1 },
    [143] = { name = "Spoils - Yagudo Bead Necklace", goal = 2 },
    [144] = { name = "Spoils - Woozyshroom", goal = 2 },
    [145] = { name = "Spoils - Beehive Chip", goal = 2 },
    [146] = { name = "Spoils - Remi Shell", goal = 2 },
    [147] = { name = "Spoils - Twinstone Earring", goal = 2 },
    [180] = { name = "Harvesting: East Ronfaure", goal = 5 },
    [181] = { name = "Harvesting: Ghelsba Outpost", goal = 5 },
    [182] = { name = "Harvesting: Gusgen Mines", goal = 5 },
    [183] = { name = "Harvesting: Jugner Forest", goal = 5 },
    [184] = { name = "Harvesting: Zeruhn Mines", goal = 5 },
    [185] = { name = "Harvesting: Palborough Mines", goal = 5 },
    [186] = { name = "Harvesting: West Sarutabaruta", goal = 5 },
    [187] = { name = "Harvesting: Giddeus", goal = 5 },
    [188] = { name = "Harvesting: Buburimu Peninsula", goal = 5 },
    [189] = { name = "Harvesting: Tahrongi Canyon", goal = 5 },
    [190] = { name = "Harvesting: Maze of Shakhrami", goal = 5 },
    [215] = { name = "Conflict: West Ronfaure", goal = 10 },
    [216] = { name = "Subjugation: Jaggedy-Eared Jack", goal = 1 },
    [217] = { name = "Conflict: East Ronfaure", goal = 10 },
    [218] = { name = "Subjugation: Swamfisk", goal = 1 },
    [219] = { name = "Conflict: Ghelsba Outpost", goal = 10 },
    [220] = { name = "Subjugation: Thousandarm Deshglesh", goal = 1 },
    [221] = { name = "Conflict: Fort Ghelsba", goal = 10 },
    [222] = { name = "Subjugation: Hundredscar Hajwaj", goal = 1 },
    [223] = { name = "Conflict: Yughott Grotto", goal = 10 },
    [224] = { name = "Subjugation: Ashmaker Gotblut", goal = 1 },
    [225] = { name = "Conflict: King Ranperre\'s Tomb", goal = 10 },
    [226] = { name = "Subjugation: Barbastelle", goal = 1 },
    [227] = { name = "Conflict: Bostaunieux Oubliette", goal = 10 },
    [228] = { name = "Subjugation: Bloodsucker", goal = 1 },
    [229] = { name = "Conflict: Valkurm Dunes", goal = 10 },
    [230] = { name = "Subjugation: Valkurm Emperor", goal = 1 },
    [231] = { name = "Conflict: Konschtat Highlands", goal = 10 },
    [232] = { name = "Subjugation: Bendigeit Vran", goal = 1 },
    [233] = { name = "Conflict: Gusgen Mines", goal = 10 },
    [234] = { name = "Subjugation: Juggler Hecatomb", goal = 1 },
    [235] = { name = "Conflict: La Theine Plateau", goal = 10 },
    [236] = { name = "Subjugation: Bloodtear Baldurf", goal = 1 },
    [237] = { name = "Conflict: Ordelle\'s Caves", goal = 10 },
    [238] = { name = "Subjugation: Morbolger", goal = 1 },
    [239] = { name = "Conflict: Jugner Forest", goal = 10 },
    [240] = { name = "Subjugation: King Arthro", goal = 1 },
    [241] = { name = "Conflict: Batallia Downs", goal = 10 },
    [242] = { name = "Subjugation: Lumber Jack", goal = 1 },
    [243] = { name = "Conflict: Eldieme Necropolis", goal = 10 },
    [244] = { name = "Subjugation: Cwn Cyrff", goal = 1 },
    [245] = { name = "Conflict: Davoi", goal = 10 },
    [246] = { name = "Subjugation: Hawkeyed Dnatbat", goal = 1 },
    [247] = { name = "Conflict: N. Gustaberg", goal = 10 },
    [248] = { name = "Subjugation: Maighdean Uaine", goal = 1 },
    [249] = { name = "Conflict: S. Gustaberg", goal = 10 },
    [250] = { name = "Subjugation: Carnero", goal = 1 },
    [251] = { name = "Conflict: Zeruhn Mines", goal = 10 },
    [252] = { name = "Conflict: Palborough Mines", goal = 10 },
    [253] = { name = "Subjugation: Zi-Ghi Bone-eater", goal = 1 },
    [254] = { name = "Conflict: Dangruf Wadi", goal = 10 },
    [255] = { name = "Subjugation: Teporingo", goal = 1 },
    [256] = { name = "Conflict: Pashhow Marshlands", goal = 10 },
    [257] = { name = "Subjugation: Ni\'Zho Bladebender", goal = 1 },
    [258] = { name = "Conflict: Rolanberry Fields", goal = 10 },
    [259] = { name = "Subjugation: Simurgh", goal = 1 },
    [260] = { name = "Conflict: Crawler\'s Nest", goal = 10 },
    [261] = { name = "Subjugation: Demonic Tiphia", goal = 1 },
    [262] = { name = "Conflict: Beadeaux", goal = 10 },
    [263] = { name = "Subjugation: Zo\'Khu Blackcloud", goal = 1 },
    [264] = { name = "Conflict: West Sarutabaruta", goal = 10 },
    [265] = { name = "Subjugation: Nunyenunc", goal = 1 },
    [266] = { name = "Conflict: East Sarutabaruta", goal = 10 },
    [267] = { name = "Subjugation: Spiny Spipi", goal = 1 },
    [268] = { name = "Conflict: Giddeus", goal = 10 },
    [269] = { name = "Subjugation: Hoo Mjuu the Torrent", goal = 1 },
    [270] = { name = "Conflict: Toraimarai Canal", goal = 10 },
    [271] = { name = "Subjugation: Oni Carcass", goal = 1 },
    [272] = { name = "Conflict: Inner Horutoto Ruins", goal = 10 },
    [273] = { name = "Subjugation: Maltha", goal = 1 },
    [274] = { name = "Conflict: Outer Horutoto Ruins", goal = 10 },
    [275] = { name = "Subjugation: Bomb King", goal = 1 },
    [276] = { name = "Conflict: Buburimu Peninsula", goal = 10 },
    [277] = { name = "Subjugation: Helldiver", goal = 1 },
    [278] = { name = "Conflict: Tahrongi Canyon", goal = 10 },
    [279] = { name = "Subjugation: Serpopard Ishtar", goal = 1 },
    [280] = { name = "Conflict: Maze of Shakhrami", goal = 10 },
    [281] = { name = "Subjugation: Argus", goal = 1 },
    [282] = { name = "Conflict: Meriphataud Mountains", goal = 10 },
    [283] = { name = "Subjugation: Daggerclaw Dracos", goal = 1 },
    [284] = { name = "Conflict: Sauromugue Champaign", goal = 10 },
    [285] = { name = "Subjugation: Roc", goal = 1 },
    [286] = { name = "Conflict: Garlaige Citadel", goal = 10 },
    [287] = { name = "Subjugation: Serket", goal = 1 },
    [288] = { name = "Conflict: Castle Oztroja", goal = 10 },
    [289] = { name = "Subjugation: Lii Jixa the Somnolist", goal = 1 },
    [290] = { name = "Conflict: Beaucedine Glacier", goal = 10 },
    [291] = { name = "Subjugation: Nue", goal = 1 },
    [292] = { name = "Conflict: Ranguemont Pass", goal = 10 },
    [293] = { name = "Subjugation: Gloom Eye", goal = 1 },
    [294] = { name = "Conflict: Fei\'Yin", goal = 10 },
    [295] = { name = "Subjugation: Goliath", goal = 1 },
    [296] = { name = "Conflict: Xarcabard", goal = 10 },
    [297] = { name = "Subjugation: Biast", goal = 1 },
    [298] = { name = "Conflict: Castle Zvahl Baileys", goal = 10 },
    [299] = { name = "Subjugation: Duke Haborym", goal = 1 },
    [300] = { name = "Conflict: Castle Zvahl Keep", goal = 10 },
    [301] = { name = "Subjugation: Baron Vapula", goal = 1 },
    [302] = { name = "Conflict: Qufim Island", goal = 10 },
    [303] = { name = "Subjugation: Dosetsu Tree", goal = 1 },
    [304] = { name = "Conflict: Lower Delkfutt\'s Tower", goal = 10 },
    [305] = { name = "Subjugation: Epialtes", goal = 1 },
    [306] = { name = "Conflict: Middle Delkfutt\'s Tower", goal = 10 },
    [307] = { name = "Subjugation: Ogygos", goal = 1 },
    [308] = { name = "Conflict: Upper Delkfutt\'s Tower", goal = 10 },
    [309] = { name = "Subjugation: Enkelados", goal = 1 },
    [310] = { name = "Conflict: Rala Waterways I", goal = 5 },
    [311] = { name = "Conflict: Rala Waterways II", goal = 5 },
    [312] = { name = "Conflict: Rala Waterways III", goal = 5 },
    [313] = { name = "Conflict: Ceizak Battlegrounds I", goal = 5 },
    [314] = { name = "Conflict: Ceizak Battlegrounds II", goal = 5 },
    [315] = { name = "Conflict: Ceizak Battlegrounds III", goal = 5 },
    [316] = { name = "Conflict: Yahse Hunting Grounds I", goal = 5 },
    [317] = { name = "Conflict: Yahse Hunting Grounds II", goal = 5 },
    [318] = { name = "Conflict: Yahse Hunting Grounds III", goal = 5 },
    [319] = { name = "Conflict: Foret de Hennitiel I", goal = 5 },
    [320] = { name = "Conflict: Foret de Hennitiel II", goal = 5 },
    [321] = { name = "Conflict: Foret de Hennitiel III", goal = 5 },
    [322] = { name = "Conflict: Morimar Basalt Fields I", goal = 5 },
    [323] = { name = "Conflict: Morimar Basalt Fields II", goal = 5 },
    [324] = { name = "Conflict: Morimar Basalt Fields III", goal = 5 },
    [325] = { name = "Conflict: Yorcia Weald I", goal = 5 },
    [326] = { name = "Conflict: Yorcia Weald II", goal = 5 },
    [327] = { name = "Conflict: Yorcia Weald III", goal = 5 },
    [328] = { name = "Conflict: Marjami Ravine I", goal = 5 },
    [329] = { name = "Conflict: Marjami Ravine II", goal = 5 },
    [330] = { name = "Conflict: Marjami Ravine III", goal = 5 },
    [331] = { name = "Conflict: Kamihr Drifts I", goal = 5 },
    [332] = { name = "Conflict: Kamihr Drifts II", goal = 5 },
    [333] = { name = "Conflict: Kamihr Drifts III", goal = 5 },
    [334] = { name = "Conflict: Sih Gates I", goal = 5 },
    [335] = { name = "Conflict: Sih Gates II", goal = 5 },
    [336] = { name = "Conflict: Sih Gates III", goal = 5 },
    [337] = { name = "Conflict: Moh Gates I", goal = 5 },
    [338] = { name = "Conflict: Moh Gates II", goal = 5 },
    [339] = { name = "Conflict: Moh Gates III", goal = 5 },
    [340] = { name = "Conflict: Cirdas Caverns I", goal = 5 },
    [341] = { name = "Conflict: Cirdas Caverns II", goal = 5 },
    [342] = { name = "Conflict: Cirdas Caverns III", goal = 5 },
    [343] = { name = "Conflict: Dho Gates I", goal = 5 },
    [344] = { name = "Conflict: Dho Gates II", goal = 5 },
    [345] = { name = "Conflict: Dho Gates III", goal = 5 },
    [346] = { name = "Conflict: Woh Gates I", goal = 5 },
    [347] = { name = "Conflict: Woh Gates II", goal = 5 },
    [348] = { name = "Conflict: Woh Gates III", goal = 5 },
    [380] = { name = "Conflict: Behemoth\'s Dominion", goal = 10 },
    [389] = { name = "Harvesting: Yughott Grotto", goal = 5 },
    [390] = { name = "Conflict: Sanctuary of Zi\'Tah", goal = 10 },
    [392] = { name = "Conflict: Ro\'Maeve", goal = 10 },
    [394] = { name = "Conflict: Boyahda Tree", goal = 10 },
    [396] = { name = "Conflict: Dragon\'s Aery", goal = 10 },
    [398] = { name = "Conflict: Eastern Altepa Desert", goal = 10 },
    [400] = { name = "Conflict: Western Altepa Desert", goal = 10 },
    [402] = { name = "Conflict: Quicksand Caves", goal = 10 },
    [404] = { name = "Conflict: Gustav Tunnel", goal = 10 },
    [406] = { name = "Conflict: Kuftal Tunnel", goal = 10 },
    [408] = { name = "Conflict: Cape Terrigan", goal = 10 },
    [410] = { name = "Conflict: Valley of Sorrows", goal = 10 },
    [412] = { name = "Conflict: Yuhtunga Jungle", goal = 10 },
    [414] = { name = "Conflict: Sea Serpent Grotto", goal = 10 },
    [416] = { name = "Conflict: Yhoator Jungle", goal = 10 },
    [418] = { name = "Conflict: Temple of Uggalepih", goal = 10 },
    [420] = { name = "Conflict: Den of Rancor", goal = 10 },
    [422] = { name = "Conflict: Ifrit\'s Cauldron", goal = 10 },
    [424] = { name = "Conflict: Ru\'Aun Gardens", goal = 10 },
    [426] = { name = "Conflict: Ve\'Lugannon Palace", goal = 10 },
    [428] = { name = "Conflict: Shrine of Ru\'Avitau", goal = 10 },
    [430] = { name = "Conflict: Labyrinth of Onzozo", goal = 10 },
    [432] = { name = "Conflict: Korroloka Tunnel", goal = 10 },
    [434] = { name = "Conflict: Oldton Movalpolos", goal = 10 },
    [436] = { name = "Conflict: Newton Movalpolos", goal = 10 },
    [438] = { name = "Conflict: Lufaise Meadows", goal = 10 },
    [440] = { name = "Conflict: Misareaux Coast", goal = 10 },
    [442] = { name = "Conflict: Phomiuna Aqueducts", goal = 10 },
    [444] = { name = "Conflict: Riverne - Site #A01", goal = 10 },
    [446] = { name = "Conflict: Riverne - Site #B01", goal = 10 },
    [448] = { name = "Conflict: Sacrarium", goal = 10 },
    [450] = { name = "Conflict: Promyvion - Holla", goal = 10 },
    [452] = { name = "Conflict: Promyvion - Dem", goal = 10 },
    [454] = { name = "Conflict: Promyvion - Mea", goal = 10 },
    [456] = { name = "Conflict: Promyvion - Vahzl", goal = 10 },
    [458] = { name = "Conflict: Al\'Taieu", goal = 10 },
    [460] = { name = "Conflict: Grand Palace of Hu\'Xzoi", goal = 10 },
    [462] = { name = "Conflict: Garden of Ru\'Hmet", goal = 10 },
    [464] = { name = "Conflict: Carpenters\' Landing", goal = 10 },
    [468] = { name = "Conflict: Bibiki Bay", goal = 10 },
    [472] = { name = "Conflict: Attohwa Chasm", goal = 10 },
    [474] = { name = "Conflict: Pso\'Xja", goal = 10 },
    [476] = { name = "Conflict: Uleguerand Range", goal = 10 },
    [478] = { name = "Harvesting: Yuhtunga Jungle", goal = 5 },
    [479] = { name = "Harvesting: Yhoator Jungle", goal = 5 },
    [480] = { name = "Harvesting: Ifrit\'s Cauldron", goal = 5 },
    [481] = { name = "Harvesting: Oldton Movalpolos", goal = 5 },
    [482] = { name = "Harvesting: Newton Movalpolos", goal = 5 },
    [483] = { name = "Harvesting: Lufaise Meadows", goal = 5 },
    [484] = { name = "Harvesting: Misareaux Coast", goal = 5 },
    [485] = { name = "Harvesting: Korroloka Tunnel", goal = 5 },
    [486] = { name = "Harvesting: Carpenters\' Landing", goal = 5 },
    [487] = { name = "Harvesting: Attohwa Chasm", goal = 5 },
    [488] = { name = "Heal for 500+ HP", goal = 100 },
    [490] = { name = "Unlock Treasure Chests and Coffers", goal = 1 },
    [494] = { name = "Conflict: Outer Ra\'Kaznar I", goal = 5 },
    [495] = { name = "Conflict: Outer Ra\'Kaznar I", goal = 5 },
    [496] = { name = "Conflict: Outer Ra\'Kaznar I", goal = 5 },
    [499] = { name = "Stepping into an Ambuscade", goal = 1 },
    [500] = { name = "Mog House Exit: San d\'Oria", goal = 1 },
    [501] = { name = "Mog House Exit: Bastok", goal = 1 },
    [502] = { name = "Mog House Exit: Windurst", goal = 1 },
    [503] = { name = "Mog House Exit: Jeuno", goal = 1 },
    [504] = { name = "Mog House Exit: Aht Urhgan", goal = 1 },
    [505] = { name = "Obtain a Support Job", goal = 1 },
    [506] = { name = "Obtain an Alter Ego: San d\'Oria", goal = 1 },
    [507] = { name = "Obtain an Alter Ego: Bastok", goal = 1 },
    [508] = { name = "Obtain an Alter Ego: Windurst", goal = 1 },
    [509] = { name = "Obtain a Chocobo License", goal = 1 },
    [510] = { name = "Obtain Job: Paladin", goal = 1 },
    [511] = { name = "Obtain Job: Dark Knight", goal = 1 },
    [512] = { name = "Obtain Job: Beastmaster", goal = 1 },
    [513] = { name = "Obtain Job: Bard", goal = 1 },
    [514] = { name = "Obtain Job: Ranger", goal = 1 },
    [515] = { name = "Obtain Job: Samurai", goal = 1 },
    [516] = { name = "Obtain Job: Ninja", goal = 1 },
    [517] = { name = "Obtain Job: Dragoon", goal = 1 },
    [518] = { name = "Obtain Job: Summoner", goal = 1 },
    [519] = { name = "Obtain Job: Blue Mage", goal = 1 },
    [520] = { name = "Obtain Job: Corsair", goal = 1 },
    [521] = { name = "Obtain Job: Puppetmaster", goal = 1 },
    [522] = { name = "Obtain Job: Dancer", goal = 1 },
    [523] = { name = "Obtain Job: Scholar", goal = 1 },
    [524] = { name = "Obtain Job: Geomancer", goal = 1 },
    [525] = { name = "Obtain Job: Runefencer", goal = 1 },
    [533] = { name = "Conflict: Bhaflau Thickets", goal = 10 },
    [535] = { name = "Conflict: Mamook", goal = 10 },
    [537] = { name = "Conflict: Wajaom Woodlands", goal = 10 },
    [539] = { name = "Conflict: Aydeewa Subterrane", goal = 10 },
    [541] = { name = "Conflict: Halvung", goal = 10 },
    [543] = { name = "Conflict: Mount Zhayolm", goal = 10 },
    [545] = { name = "Conflict: Caedarva Mire", goal = 10 },
    [547] = { name = "Conflict: Arrapago Reef", goal = 10 },
    [549] = { name = "Conflict: Alza. Undersea Ruins", goal = 10 },
    [553] = { name = "Conflict: East Ronfaure [S]", goal = 10 },
    [555] = { name = "Conflict: Jugner Forest [S]", goal = 10 },
    [557] = { name = "Conflict: Batallia Downs [S]", goal = 10 },
    [559] = { name = "Conflict: La Vaule [S]", goal = 10 },
    [561] = { name = "Conflict: Eldieme Necropolis [S]", goal = 10 },
    [563] = { name = "Conflict: North Gustaberg [S]", goal = 10 },
    [565] = { name = "Conflict: Grauberg [S]", goal = 10 },
    [567] = { name = "Conflict: Vunkerl Inlet [S]", goal = 10 },
    [569] = { name = "Conflict: Pashhow Marshlands [S]", goal = 10 },
    [571] = { name = "Conflict: Rolanberry Fields [S]", goal = 10 },
    [573] = { name = "Conflict: Beadeaux [S]", goal = 10 },
    [575] = { name = "Conflict: Crawlers\' Nest [S]", goal = 10 },
    [577] = { name = "Conflict: West Sarutabaruta [S]", goal = 10 },
    [579] = { name = "Conflict: Fort Karugo-Narugo [S]", goal = 10 },
    [581] = { name = "Conflict: Meriph. Mountains [S]", goal = 10 },
    [583] = { name = "Conflict: Sauro. Champaign [S]", goal = 10 },
    [585] = { name = "Conflict: Castle Oztroja [S]", goal = 10 },
    [587] = { name = "Conflict: Garlaige Citadel [S]", goal = 10 },
    [589] = { name = "Conflict: Beaucedine Glacier [S]", goal = 10 },
    [591] = { name = "Conflict: Xarcabard [S]", goal = 10 },
    [593] = { name = "Conflict: Castle Zvahl Baileys [S]", goal = 10 },
    [595] = { name = "Conflict: Castle Zvahl Keep [S]", goal = 10 },
    [599] = { name = "Harvesting: Bhaflau Thickets", goal = 5 },
    [600] = { name = "Harvesting: Mamook", goal = 5 },
    [601] = { name = "Harvesting: Wajaom Woodlands", goal = 5 },
    [602] = { name = "Harvesting: Halvung", goal = 5 },
    [603] = { name = "Harvesting: Mount Zhayolm", goal = 5 },
    [604] = { name = "Harvesting: Caedarva Mire", goal = 5 },
    [606] = { name = "Harvesting: East Ronfaure [S]", goal = 5 },
    [607] = { name = "Harvesting: Jugner Forest [S]", goal = 5 },
    [608] = { name = "Harvesting: North Gustaberg [S]", goal = 5 },
    [609] = { name = "Harvesting: Grauberg [S]", goal = 5 },
    [610] = { name = "Harvesting: West Sarutabaruta [S]", goal = 5 },
    [611] = { name = "Harvesting: Fort Karugo-Narugo [S]", goal = 5 },
    [613] = { name = "Conflict: Abyssea - La Theine", goal = 30 },
    [614] = { name = "Conflict: Abyssea - Konschtat", goal = 30 },
    [615] = { name = "Conflict: Abyssea - Tahrongi", goal = 30 },
    [616] = { name = "Conflict: Abyssea - Attohwa", goal = 30 },
    [617] = { name = "Conflict: Abyssea - Misareaux", goal = 30 },
    [618] = { name = "Conflict: Abyssea - Vunkerl", goal = 30 },
    [619] = { name = "Conflict: Abyssea - Altepa", goal = 30 },
    [620] = { name = "Conflict: Abyssea - Uleguerand", goal = 30 },
    [621] = { name = "Conflict: Abyssea - Grauberg", goal = 30 },
    [629] = { name = "WAR Artifact Quest I", goal = 1 },
    [630] = { name = "WAR Artifact Quest II", goal = 1 },
    [631] = { name = "WAR Artifact Quest III", goal = 1 },
    [632] = { name = "MNK Artifact Quest I", goal = 1 },
    [633] = { name = "MNK Artifact Quest II", goal = 1 },
    [634] = { name = "MNK Artifact Quest III", goal = 1 },
    [635] = { name = "WHM Artifact Quest I", goal = 1 },
    [636] = { name = "WHM Artifact Quest II", goal = 1 },
    [637] = { name = "WHM Artifact Quest III", goal = 1 },
    [638] = { name = "BLM Artifact Quest I", goal = 1 },
    [639] = { name = "BLM Artifact Quest II", goal = 1 },
    [640] = { name = "BLM Artifact Quest III", goal = 1 },
    [641] = { name = "RDM Artifact Quest I", goal = 1 },
    [642] = { name = "RDM Artifact Quest II", goal = 1 },
    [643] = { name = "RDM Artifact Quest III", goal = 1 },
    [644] = { name = "THF Artifact Quest I", goal = 1 },
    [645] = { name = "THF Artifact Quest II", goal = 1 },
    [646] = { name = "THF Artifact Quest III", goal = 1 },
    [647] = { name = "PLD Artifact Quest I", goal = 1 },
    [648] = { name = "PLD Artifact Quest II", goal = 1 },
    [649] = { name = "PLD Artifact Quest III", goal = 1 },
    [650] = { name = "DRK Artifact Quest I", goal = 1 },
    [651] = { name = "DRK Artifact Quest II", goal = 1 },
    [652] = { name = "DRK Artifact Quest III", goal = 1 },
    [653] = { name = "BST Artifact Quest I", goal = 1 },
    [654] = { name = "BST Artifact Quest II", goal = 1 },
    [655] = { name = "BST Artifact Quest III", goal = 1 },
    [656] = { name = "BRD Artifact Quest I", goal = 1 },
    [657] = { name = "BRD Artifact Quest II", goal = 1 },
    [658] = { name = "BRD Artifact Quest III", goal = 1 },
    [659] = { name = "RNG Artifact Quest I", goal = 1 },
    [660] = { name = "RNG Artifact Quest II", goal = 1 },
    [661] = { name = "RNG Artifact Quest III", goal = 1 },
    [662] = { name = "SAM Artifact Quest I", goal = 1 },
    [663] = { name = "SAM Artifact Quest II", goal = 1 },
    [664] = { name = "SAM Artifact Quest III", goal = 1 },
    [665] = { name = "NIN Artifact Quest I", goal = 1 },
    [666] = { name = "NIN Artifact Quest II", goal = 1 },
    [667] = { name = "NIN Artifact Quest III", goal = 1 },
    [668] = { name = "DRG Artifact Quest I", goal = 1 },
    [669] = { name = "DRG Artifact Quest II", goal = 1 },
    [670] = { name = "DRG Artifact Quest III", goal = 1 },
    [671] = { name = "SMN Artifact Quest I", goal = 1 },
    [672] = { name = "SMN Artifact Quest II", goal = 1 },
    [673] = { name = "SMN Artifact Quest III", goal = 1 },
    [674] = { name = "BLU Artifact Quest I", goal = 1 },
    [675] = { name = "BLU Artifact Quest II", goal = 1 },
    [676] = { name = "BLU Artifact Quest III", goal = 1 },
    [677] = { name = "COR Artifact Quest I", goal = 1 },
    [678] = { name = "COR Artifact Quest II", goal = 1 },
    [679] = { name = "COR Artifact Quest III", goal = 1 },
    [680] = { name = "PUP Artifact Quest I", goal = 1 },
    [681] = { name = "PUP Artifact Quest II", goal = 1 },
    [682] = { name = "PUP Artifact Quest III", goal = 1 },
    [683] = { name = "DNC Artifact Quest I", goal = 1 },
    [684] = { name = "DNC Artifact Quest II", goal = 1 },
    [685] = { name = "DNC Artifact Quest III", goal = 1 },
    [686] = { name = "SCH Artifact Quest I", goal = 1 },
    [687] = { name = "SCH Artifact Quest II", goal = 1 },
    [688] = { name = "SCH Artifact Quest III", goal = 1 },
    [689] = { name = "GEO Artifact Quest I", goal = 1 },
    [690] = { name = "GEO Artifact Quest II", goal = 1 },
    [691] = { name = "GEO Artifact Quest III", goal = 1 },
    [692] = { name = "RUN Artifact Quest I", goal = 1 },
    [693] = { name = "RUN Artifact Quest II", goal = 1 },
    [694] = { name = "RUN Artifact Quest III", goal = 1 },
    [696] = { name = "Total Damage III", goal = 300000 },
    [697] = { name = "Total Damage Taken III", goal = 30000 },
    [698] = { name = "Deal 2000+ Damage", goal = 100 },
    [699] = { name = "Total Healing III", goal = 30000 },
    [700] = { name = "Heal for 750+ HP", goal = 100 },
    [705] = { name = "Level Cap Increase: 55 +", goal = 1 },
    [706] = { name = "Level Cap Increase: 60", goal = 1 },
    [707] = { name = "Level Cap Increase: 65", goal = 1 },
    [708] = { name = "Level Cap Increase: 70", goal = 1 },
    [709] = { name = "Level Cap Increase: 75", goal = 1 },
    [710] = { name = "Level Cap Increase: 80", goal = 1 },
    [711] = { name = "Level Cap Increase: 85", goal = 1 },
    [712] = { name = "Level Cap Increase: 90", goal = 1 },
    [713] = { name = "Level Cap Increase: 95", goal = 1 },
    [714] = { name = "Level Cap Increase: 99", goal = 1 },
    [715] = { name = "Inventory Expansion 35", goal = 1 },
    [716] = { name = "Inventory Expansion 40", goal = 1 },
    [717] = { name = "Inventory Expansion 45", goal = 1 },
    [718] = { name = "Inventory Expansion 50", goal = 1 },
    [719] = { name = "Inventory Expansion 55", goal = 1 },
    [720] = { name = "Inventory Expansion 60", goal = 1 },
    [721] = { name = "Inventory Expansion 65", goal = 1 },
    [722] = { name = "Inventory Expansion 70", goal = 1 },
    [723] = { name = "Inventory Expansion 75", goal = 1 },
    [724] = { name = "Inventory Expansion 80", goal = 1 },
    [726] = { name = "Reaching the Crest", goal = 1 },
    [727] = { name = "Subjugation: Kirin", goal = 1 },
    [728] = { name = "Subjugation: Genbu", goal = 1 },
    [729] = { name = "Subjugation: Suzaku", goal = 1 },
    [730] = { name = "Subjugation: Seiryu", goal = 1 },
    [731] = { name = "Subjugation: Byakko", goal = 1 },
    [732] = { name = "Subjugation: Overlord\'s Tombstone", goal = 1 },
    [733] = { name = "Subjugation: Bladeburner Rokgevok", goal = 1 },
    [734] = { name = "Subjugation: Steelshank Kratzvatz", goal = 1 },
    [735] = { name = "Subjugation: Bloodfist Voshgrosh", goal = 1 },
    [736] = { name = "Subjugation: Spellspear Djokvukk", goal = 1 },
    [737] = { name = "Subjugation: Gu\'Dha Effigy", goal = 1 },
    [738] = { name = "Subjugation: Zo\'Pha Forgesoul", goal = 1 },
    [739] = { name = "Subjugation: Ra\'Gho Darkfount", goal = 1 },
    [740] = { name = "Subjugation: Va\'Zhe Pummelsong", goal = 1 },
    [741] = { name = "Subjugation: Bu\'Bho Truesteel", goal = 1 },
    [742] = { name = "Subjugation: Tzee Xicu Idol", goal = 1 },
    [743] = { name = "Subjugation: Xuu Bhoqa the Enigma", goal = 1 },
    [744] = { name = "Subjugation: Fuu Tzapo the Blessed", goal = 1 },
    [745] = { name = "Subjugation: Naa Yixo the Stillrage", goal = 1 },
    [746] = { name = "Subjugation: Tee Zaska the Ceaseless", goal = 1 },
    [747] = { name = "Subjugation: Goblin Golem", goal = 1 },
    [748] = { name = "Subjugation: Quicktrix Hexhands", goal = 1 },
    [749] = { name = "Subjugation: Feralox Honeylips", goal = 1 },
    [750] = { name = "Subjugation: Scourquix Scaleskin", goal = 1 },
    [751] = { name = "Subjugation: Wilywox Tenderpalm", goal = 1 },
    [752] = { name = "Subjugation: Angra Mainyu", goal = 1 },
    [753] = { name = "Subjugation: Taquede", goal = 1 },
    [754] = { name = "Subjugation: Pignonpausard", goal = 1 },
    [755] = { name = "Subjugation: Hitaume", goal = 1 },
    [756] = { name = "Subjugation: Cavanneche", goal = 1 },
    [757] = { name = "Subjugation: Dynamis Lord", goal = 1 },
    [758] = { name = "Subjugation: Duke Haures", goal = 1 },
    [759] = { name = "Subjugation: Marquis Caim", goal = 1 },
    [760] = { name = "Subjugation: Baron Avnas", goal = 1 },
    [761] = { name = "Subjugation: Count Haagenti", goal = 1 },
    [762] = { name = "Conflict: Ra\'Kaznar Inner Court I", goal = 5 },
    [763] = { name = "Conflict: Ra\'Kaznar Inner Court II", goal = 5 },
    [764] = { name = "Conflict: Ra\'Kaznar Inner Court III", goal = 5 },
    [768] = { name = "Subjugation: Jailer of Justice", goal = 1 },
    [769] = { name = "Subjugation: Jailer of Hope", goal = 1 },
    [770] = { name = "Subjugation: Jailer of Prudence is handled in mob script", goal = 1 },
    [771] = { name = "Subjugation: Jailer of Love", goal = 1 },
    [772] = { name = "Spoils - Ivory Chip", goal = 1 },
    [773] = { name = "Spoils - Scarlet Chip", goal = 1 },
    [774] = { name = "Spoils - Emerald Chip", goal = 1 },
    [775] = { name = "Spoils - Orchid Chip", goal = 1 },
    [776] = { name = "Spoils - Cerulean Chip", goal = 1 },
    [777] = { name = "Spoils - Silver Chip", goal = 1 },
    [778] = { name = "Spoils - Smoky Chip", goal = 1 },
    [779] = { name = "Spoils - Magenta Chip", goal = 1 },
    [780] = { name = "Spoils - Charcoal Chip", goal = 1 },
    [781] = { name = "Spoils - Smalt Chip", goal = 1 },
    [782] = { name = "Subjugation: Proto-Ultima", goal = 1 },
    [783] = { name = "Subjugation: Proto-Omega", goal = 1 },
    [785] = { name = "Subjugation: Vulpangue", goal = 1 },
    [786] = { name = "Subjugation: Chamrosh", goal = 1 },
    [787] = { name = "Subjugation: Cheese Hoarder Gigiroon", goal = 1 },
    [788] = { name = "Subjugation: Brass Borer", goal = 1 },
    [789] = { name = "Subjugation: Claret", goal = 1 },
    [790] = { name = "Subjugation: Ob", goal = 1 },
    [791] = { name = "Subjugation: Velionis", goal = 1 },
    [792] = { name = "Subjugation Lil\' Apkallu", goal = 1 },
    [793] = { name = "Subjugation: Chigre", goal = 1 },
    [794] = { name = "Subjugation: Iriz Ima", goal = 1 },
    [795] = { name = "Subjugation: Lividroot Amooshah", goal = 1 },
    [796] = { name = "Subjugation: Iriri Samariri", goal = 1 },
    [797] = { name = "Subjugation: Anantaboga", goal = 1 },
    [798] = { name = "Subjugation: Reacton", goal = 1 },
    [799] = { name = "Subjugation: Dextrose", goal = 1 },
    [800] = { name = "Subjugation: Wulgaru", goal = 1 },
    [801] = { name = "Subjugation: Zareehkl the Jubilant", goal = 1 },
    [802] = { name = "Subjugation: Verdelet", goal = 1 },
    [803] = { name = "Subjugation: Armed Gears", goal = 1 },
    [804] = { name = "Subjugation: Gotoh Zha the Redolent", goal = 1 },
    [805] = { name = "Subjugation: Dea", goal = 1 },
    [806] = { name = "Subjugation: Nosferatu", goal = 1 },
    [807] = { name = "Subjugation: Khromasoul Bhurborlor", goal = 1 },
    [808] = { name = "Subjugation: Achamoth", goal = 1 },
    [809] = { name = "Subjugation: Mahjlaef the Paintorn", goal = 1 },
    [810] = { name = "Subjugation: Experimental Lamia", goal = 1 },
    [811] = { name = "Subjugation: Nuhn", goal = 1 },
    [812] = { name = "Subjugation: Battleclad Chariot", goal = 1 },
    [813] = { name = "Subjugation: Armored Chariot", goal = 1 },
    [814] = { name = "Subjugation: Long-Bowed Chariot", goal = 1 },
    [815] = { name = "Subjugation: Long-Armed Chariot", goal = 1 },
    [839] = { name = "Asuran Fists", goal = 1 },
    [840] = { name = "Evisceration", goal = 1 },
    [841] = { name = "Savage Blade", goal = 1 },
    [842] = { name = "Ground Strike", goal = 1 },
    [843] = { name = "Decimation", goal = 1 },
    [844] = { name = "Steel Cyclone", goal = 1 },
    [845] = { name = "Spiral Hell", goal = 1 },
    [846] = { name = "Impulse Drive", goal = 1 },
    [847] = { name = "Blade: Ku", goal = 1 },
    [848] = { name = "Tachi: Kasha", goal = 1 },
    [849] = { name = "Black Halo", goal = 1 },
    [850] = { name = "Retribution", goal = 1 },
    [851] = { name = "Empyreal Arrow", goal = 1 },
    [852] = { name = "Detonator", goal = 1 },
    [885] = { name = "Conflict: Escha - Zi\'Tah I", goal = 10 },
    [886] = { name = "Conflict: Escha - Zi\'Tah II", goal = 10 },
    [887] = { name = "Conflict: Escha - Zi\'Tah III", goal = 10 },
    [888] = { name = "Conflict: Escha - Zi\'Tah IV", goal = 10 },
    [889] = { name = "Conflict: Escha - Zi\'Tah V", goal = 10 },
    [901] = { name = "Conflict: Escha - Zi\'Tah VI", goal = 10 },
    [902] = { name = "Conflict: Escha - Zi\'Tah VII", goal = 10 },
    [903] = { name = "Conflict: Escha - Ru\'Aun I", goal = 10 },
    [904] = { name = "Conflict: Escha - Ru\'Aun II", goal = 10 },
    [905] = { name = "Conflict: Escha - Ru\'Aun III", goal = 10 },
    [906] = { name = "Conflict: Escha - Ru\'Aun IV", goal = 10 },
    [907] = { name = "Conflict: Escha - Ru\'Aun V", goal = 10 },
    [908] = { name = "Conflict: Escha - Ru\'Aun VI", goal = 10 },
    [909] = { name = "Conflict: Escha - Ru\'Aun VII", goal = 10 },
    [910] = { name = "Conflict: Escha - Ru\'Aun VIII", goal = 10 },
    [911] = { name = "Conflict: Escha - Ru\'Aun IX", goal = 10 },
    [912] = { name = "Conflict: Escha - Ru\'Aun X", goal = 10 },
    [932] = { name = "Call Forth an Alter Ego (gives Cipher: Valaineral)", goal = 1 },
    [933] = { name = "Alter Ego: Valaineral (gives Cipher: Mihli)", goal = 1 },
    [934] = { name = "Alter Ego: Mihli Aliapoh (gives Cipher: Tenzen)", goal = 1 },
    [935] = { name = "Alter Ego: Tenzen (gives Cipher: Adelheid)", goal = 1 },
    [936] = { name = "Alter Ego: Adelheid (gives Cipher: Joachim)", goal = 1 },
    [937] = { name = "Alter Ego: Joachim", goal = 1 },
    [939] = { name = "Mog Safe Expansion: 60", goal = 1 },
    [940] = { name = "Mog Safe Expansion: 70", goal = 1 },
    [941] = { name = "Mog Safe Expansion: 80", goal = 1 },
    [943] = { name = "Conflict: Reisenjima I", goal = 10 },
    [944] = { name = "Conflict: Reisenjima II", goal = 10 },
    [945] = { name = "Conflict: Reisenjima III", goal = 10 },
    [946] = { name = "Conflict: Reisenjima IV", goal = 10 },
    [947] = { name = "Conflict: Reisenjima V", goal = 10 },
    [948] = { name = "Conflict: Reisenjima VI", goal = 10 },
    [949] = { name = "Conflict: Reisenjima VII", goal = 10 },
    [950] = { name = "Conflict: Reisenjima VIII", goal = 10 },
    [951] = { name = "Conflict: Reisenjima IX", goal = 10 },
    [952] = { name = "Conflict: Reisenjima X", goal = 10 },
    [953] = { name = "Conflict: Reisenjima XI", goal = 10 },
    [1045] = { name = "Achieve Level 99 (gives Kupon A-PK109 x5)", goal = 1 },
    [1046] = { name = "An Eminent Scholar (gives Kupon W-EMI)", goal = 1 },
    [1047] = { name = "An Eminent Scholar 2 (gives Kupon A-EMI)", goal = 1 },
    [1048] = { name = "An Eminent Scholar 3 (gives Kupon A-EMI)", goal = 1 },
    [1049] = { name = "Always Stand on 117 (gives Cipher: Koru-Moru)", goal = 1 },
    [1200] = { name = "Level 30 Warrior +", goal = 1 },
    [1201] = { name = "Level 50 Warrior", goal = 1 },
    [1202] = { name = "Level 75 Warrior", goal = 1 },
    [1203] = { name = "Level 99 Warrior", goal = 1 },
    [1204] = { name = "Level 30 Monk", goal = 1 },
    [1205] = { name = "Level 50 Monk", goal = 1 },
    [1206] = { name = "Level 75 Monk", goal = 1 },
    [1207] = { name = "Level 99 Monk", goal = 1 },
    [1208] = { name = "Level 30 White Mage", goal = 1 },
    [1209] = { name = "Level 50 White Mage", goal = 1 },
    [1210] = { name = "Level 75 White Mage", goal = 1 },
    [1211] = { name = "Level 99 White Mage", goal = 1 },
    [1212] = { name = "Level 30 Black Mage", goal = 1 },
    [1213] = { name = "Level 50 Black Mage", goal = 1 },
    [1214] = { name = "Level 75 Black Mage", goal = 1 },
    [1215] = { name = "Level 99 Black Mage", goal = 1 },
    [1216] = { name = "Level 30 Red Mage", goal = 1 },
    [1217] = { name = "Level 50 Red Mage", goal = 1 },
    [1218] = { name = "Level 75 Red Mage", goal = 1 },
    [1219] = { name = "Level 99 Red Mage", goal = 1 },
    [1220] = { name = "Level 30 Thief", goal = 1 },
    [1221] = { name = "Level 50 Thief", goal = 1 },
    [1222] = { name = "Level 75 Thief", goal = 1 },
    [1223] = { name = "Level 99 Thief", goal = 1 },
    [1224] = { name = "Level 30 Paladin", goal = 1 },
    [1225] = { name = "Level 50 Paladin", goal = 1 },
    [1226] = { name = "Level 75 Paladin", goal = 1 },
    [1227] = { name = "Level 99 Paladin", goal = 1 },
    [1228] = { name = "Level 30 Dark Knight", goal = 1 },
    [1229] = { name = "Level 50 Dark Knight", goal = 1 },
    [1230] = { name = "Level 75 Dark Knight", goal = 1 },
    [1231] = { name = "Level 99 Dark Knight", goal = 1 },
    [1232] = { name = "Level 30 Beastmaster", goal = 1 },
    [1233] = { name = "Level 50 Beastmaster", goal = 1 },
    [1234] = { name = "Level 75 Beastmaster", goal = 1 },
    [1235] = { name = "Level 99 Beastmaster", goal = 1 },
    [1236] = { name = "Level 30 Bard", goal = 1 },
    [1237] = { name = "Level 50 Bard", goal = 1 },
    [1238] = { name = "Level 75 Bard", goal = 1 },
    [1239] = { name = "Level 99 Bard", goal = 1 },
    [1240] = { name = "Level 30 Ranger", goal = 1 },
    [1241] = { name = "Level 50 Ranger", goal = 1 },
    [1242] = { name = "Level 75 Ranger", goal = 1 },
    [1243] = { name = "Level 99 Ranger", goal = 1 },
    [1244] = { name = "Level 30 Samurai", goal = 1 },
    [1245] = { name = "Level 50 Samurai", goal = 1 },
    [1246] = { name = "Level 75 Samurai", goal = 1 },
    [1247] = { name = "Level 99 Samurai", goal = 1 },
    [1248] = { name = "Level 30 Ninja", goal = 1 },
    [1249] = { name = "Level 50 Ninja", goal = 1 },
    [1250] = { name = "Level 75 Ninja", goal = 1 },
    [1251] = { name = "Level 99 Ninja", goal = 1 },
    [1252] = { name = "Level 30 Dragoon", goal = 1 },
    [1253] = { name = "Level 50 Dragoon", goal = 1 },
    [1254] = { name = "Level 75 Dragoon", goal = 1 },
    [1255] = { name = "Level 99 Dragoon", goal = 1 },
    [1256] = { name = "Level 30 Summoner", goal = 1 },
    [1257] = { name = "Level 50 Summoner", goal = 1 },
    [1258] = { name = "Level 75 Summoner", goal = 1 },
    [1259] = { name = "Level 99 Summoner", goal = 1 },
    [1260] = { name = "Level 30 Blue Mage", goal = 1 },
    [1261] = { name = "Level 50 Blue Mage", goal = 1 },
    [1262] = { name = "Level 75 Blue Mage", goal = 1 },
    [1263] = { name = "Level 99 Blue Mage", goal = 1 },
    [1264] = { name = "Level 30 Corsair", goal = 1 },
    [1265] = { name = "Level 50 Corsair", goal = 1 },
    [1266] = { name = "Level 75 Corsair", goal = 1 },
    [1267] = { name = "Level 99 Corsair", goal = 1 },
    [1268] = { name = "Level 30 Puppetmaster", goal = 1 },
    [1269] = { name = "Level 50 Puppetmaster", goal = 1 },
    [1270] = { name = "Level 75 Puppetmaster", goal = 1 },
    [1271] = { name = "Level 99 Puppetmaster", goal = 1 },
    [1272] = { name = "Level 30 Dancer", goal = 1 },
    [1273] = { name = "Level 50 Dancer", goal = 1 },
    [1274] = { name = "Level 75 Dancer", goal = 1 },
    [1275] = { name = "Level 99 Dancer", goal = 1 },
    [1276] = { name = "Level 30 Scholar", goal = 1 },
    [1277] = { name = "Level 50 Scholar", goal = 1 },
    [1278] = { name = "Level 75 Scholar", goal = 1 },
    [1279] = { name = "Level 99 Scholar", goal = 1 },
    [1280] = { name = "Level 30 Geomancer", goal = 1 },
    [1281] = { name = "Level 50 Geomancer", goal = 1 },
    [1282] = { name = "Level 75 Geomancer", goal = 1 },
    [1283] = { name = "Level 99 Geomancer", goal = 1 },
    [1284] = { name = "Level 30 Runefencer", goal = 1 },
    [1285] = { name = "Level 50 Runefencer", goal = 1 },
    [1286] = { name = "Level 75 Runefencer", goal = 1 },
    [1287] = { name = "Level 99 Runefencer", goal = 1 },
    [1313] = { name = "San d\'Oria Rank 1-1", goal = 1 },
    [1314] = { name = "San d\'Oria Rank 1-2", goal = 1 },
    [1315] = { name = "San d\'Oria Rank 1-3", goal = 1 },
    [1316] = { name = "San d\'Oria Rank 2-1", goal = 1 },
    [1317] = { name = "San d\'Oria Rank 2-2", goal = 1 },
    [1318] = { name = "San d\'Oria Rank 2-3", goal = 1 },
    [1319] = { name = "San d\'Oria Rank 3-1", goal = 1 },
    [1320] = { name = "San d\'Oria Rank 3-2", goal = 1 },
    [1321] = { name = "San d\'Oria Rank 3-3", goal = 1 },
    [1322] = { name = "San d\'Oria Rank 4", goal = 1 },
    [1323] = { name = "San d\'Oria Rank 5-1", goal = 1 },
    [1324] = { name = "San d\'Oria Rank 5-2", goal = 1 },
    [1325] = { name = "San d\'Oria Rank 6-1", goal = 1 },
    [1326] = { name = "San d\'Oria Rank 6-2", goal = 1 },
    [1327] = { name = "San d\'Oria Rank 7-1", goal = 1 },
    [1328] = { name = "San d\'Oria Rank 7-2", goal = 1 },
    [1329] = { name = "San d\'Oria Rank 8-1", goal = 1 },
    [1330] = { name = "San d\'Oria Rank 8-2", goal = 1 },
    [1331] = { name = "San d\'Oria Rank 9-1", goal = 1 },
    [1332] = { name = "San d\'Oria Rank 9-2", goal = 1 },
    [1333] = { name = "Bastok Rank 1-1", goal = 1 },
    [1334] = { name = "Bastok Rank 1-2", goal = 1 },
    [1335] = { name = "Bastok Rank 1-3", goal = 1 },
    [1336] = { name = "Bastok Rank 2-1", goal = 1 },
    [1337] = { name = "Bastok Rank 2-2", goal = 1 },
    [1338] = { name = "Bastok Rank 2-3", goal = 1 },
    [1339] = { name = "Bastok Rank 3-1", goal = 1 },
    [1340] = { name = "Bastok Rank 3-2", goal = 1 },
    [1341] = { name = "Bastok Rank 3-3", goal = 1 },
    [1342] = { name = "Bastok Rank 4", goal = 1 },
    [1343] = { name = "Bastok Rank 5-1", goal = 1 },
    [1344] = { name = "Bastok Rank 5-2", goal = 1 },
    [1345] = { name = "Bastok Rank 6-1", goal = 1 },
    [1346] = { name = "Bastok Rank 6-2", goal = 1 },
    [1347] = { name = "Bastok Rank 7-1", goal = 1 },
    [1348] = { name = "Bastok Rank 7-2", goal = 1 },
    [1349] = { name = "Bastok Rank 8-1", goal = 1 },
    [1350] = { name = "Bastok Rank 8-2", goal = 1 },
    [1351] = { name = "Bastok Rank 9-1", goal = 1 },
    [1352] = { name = "Bastok Rank 9-2", goal = 1 },
    [1353] = { name = "Windurst Rank 1-1 +", goal = 1 },
    [1354] = { name = "Windurst Rank 1-2 +", goal = 1 },
    [1355] = { name = "Windurst Rank 1-3 +", goal = 1 },
    [1356] = { name = "Windurst Rank 2-1 +", goal = 1 },
    [1357] = { name = "Windurst Rank 2-2 +", goal = 1 },
    [1358] = { name = "Windurst Rank 2-3 +", goal = 1 },
    [1359] = { name = "Windurst Rank 3-1 +", goal = 1 },
    [1360] = { name = "Windurst Rank 3-2 +", goal = 1 },
    [1361] = { name = "Windurst Rank 3-3 +", goal = 1 },
    [1362] = { name = "Windurst Rank 4 +", goal = 1 },
    [1363] = { name = "Windurst Rank 5-1 +", goal = 1 },
    [1364] = { name = "Windurst Rank 5-2 +", goal = 1 },
    [1365] = { name = "Windurst Rank 6-1", goal = 1 },
    [1366] = { name = "Windurst Rank 6-2", goal = 1 },
    [1367] = { name = "Windurst Rank 7-1", goal = 1 },
    [1368] = { name = "Windurst Rank 7-2", goal = 1 },
    [1369] = { name = "Windurst Rank 8-1", goal = 1 },
    [1370] = { name = "Windurst Rank 8-2", goal = 1 },
    [1371] = { name = "Windurst Rank 9-1", goal = 1 },
    [1372] = { name = "Windurst Rank 9-2", goal = 1 },
    [1373] = { name = "Rhapsodies of Vana\'diel 1-1 +", goal = 1 },
    [1374] = { name = "Rhapsodies of Vana\'diel 1-2 +", goal = 1 },
    [1375] = { name = "Rhapsodies of Vana\'diel 1-3 +", goal = 1 },
    [1377] = { name = "Zilart Mission 1 +", goal = 1 },
    [1378] = { name = "Zilart Mission 2 +", goal = 1 },
    [1379] = { name = "Zilart Mission 3 +", goal = 1 },
    [1380] = { name = "Zilart Mission 4 +", goal = 1 },
    [1381] = { name = "Zilart Mission 5 +", goal = 1 },
    [1382] = { name = "Zilart Mission 6 +", goal = 1 },
    [1383] = { name = "Zilart Mission 7 +", goal = 1 },
    [1384] = { name = "Zilart Mission 8 +", goal = 1 },
    [1385] = { name = "Zilart Mission 9 +", goal = 1 },
    [1386] = { name = "Zilart Mission 10 +", goal = 1 },
    [1387] = { name = "Zilart Mission 11 +", goal = 1 },
    [1388] = { name = "Zilart Mission 12 +", goal = 1 },
    [1389] = { name = "Zilart Mission 13 +", goal = 1 },
    [1390] = { name = "Zilart Mission 14 +", goal = 1 },
    [1391] = { name = "Zilart Mission 15 +", goal = 1 },
    [1392] = { name = "Zilart Mission 16 +", goal = 1 },
    [1393] = { name = "Chains of Promathia Chapter 1 +", goal = 1 },
    [1394] = { name = "Chains of Promathia Chapter 2 +", goal = 1 },
    [1395] = { name = "Chains of Promathia Chapter 3", goal = 1 },
    [1396] = { name = "Chains of Promathia Chapter 4", goal = 1 },
    [1397] = { name = "Chains of Promathia Chapter 5", goal = 1 },
    [1398] = { name = "Chains of Promathia Chapter 6", goal = 1 },
    [1399] = { name = "Chains of Promathia Chapter 7", goal = 1 },
    [1400] = { name = "Chains of Promathia Chapter 8", goal = 1 },
    [1402] = { name = "Wings of the Goddess 1", goal = 1 },
    [1403] = { name = "Wings of the Goddess 2", goal = 1 },
    [1404] = { name = "Wings of the Goddess 3", goal = 1 },
    [1405] = { name = "Wings of the Goddess 4", goal = 1 },
    [1406] = { name = "Wings of the Goddess 5", goal = 1 },
    [1407] = { name = "Wings of the Goddess 6", goal = 1 },
    [1408] = { name = "Wings of the Goddess 7", goal = 1 },
    [1409] = { name = "Wings of the Goddess 8", goal = 1 },
    [1410] = { name = "Treasures of Aht Urhgan 1", goal = 1 },
    [1411] = { name = "Treasures of Aht Urhgan 2", goal = 1 },
    [1412] = { name = "Treasures of Aht Urhgan 3", goal = 1 },
    [1413] = { name = "Treasures of Aht Urhgan 4", goal = 1 },
    [1414] = { name = "Treasures of Aht Urhgan 5", goal = 1 },
    [1415] = { name = "Treasures of Aht Urhgan 6", goal = 1 },
    [1416] = { name = "Rhapsodies of Vana\'diel 2-1", goal = 1 },
    [1426] = { name = "Seekers of Adoulin Chapter 1", goal = 1 },
    [1427] = { name = "Seekers of Adoulin Chapter 2", goal = 1 },
    [1428] = { name = "Seekers of Adoulin Chapter 3", goal = 1 },
    [1429] = { name = "Seekers of Adoulin Chapter 4", goal = 1 },
    [1430] = { name = "Seekers of Adoulin Chapter 5", goal = 1 },
    [1447] = { name = "Exploring the Trove", goal = 1 },
    [1448] = { name = "Assist Channel", goal = 1 },
    [3000] = { name = "Unity Communique A (UC)", goal = 1 },
    [3002] = { name = "Vanquish Multiple Enemies A (UC)", goal = 20 },
    [3003] = { name = "Vanquish Aquans A (UC)", goal = 20 },
    [3004] = { name = "Vanquish Amorphs with Physical Damage A (UC)", goal = 20 },
    [3005] = { name = "Vanquish Beasts with Magic A (UC)", goal = 20 },
    [3006] = { name = "Total Successful Woodworking Syntheses A (UC)", goal = 10 },
    [3007] = { name = "Total Successful Leatherworking Syntheses A (UC)", goal = 10 },
    [3008] = { name = "Total Suc. Mining Attempts A (UC)", goal = 10 },
    [3009] = { name = "Unity Communique B (UC)", goal = 1 },
    [3010] = { name = "Chocobo Digging B (UC)", goal = 10 },
    [3011] = { name = "Vanquish Multiple Enemies B (UC)", goal = 20 },
    [3012] = { name = "Vanquish Arcana B (UC)", goal = 20 },
    [3013] = { name = "Vanquish Undead with Physical Damage B (UC)", goal = 20 },
    [3014] = { name = "Vanquish Plantoids with Magic B (UC)", goal = 20 },
    [3015] = { name = "Total Successful Blacksmithing Syntheses B (UC)", goal = 10 },
    [3017] = { name = "Total Suc. Logging Attempts B (UC)", goal = 10 },
    [3018] = { name = "Unity Communique C (UC)", goal = 1 },
    [3020] = { name = "Vanquish Multiple Enemies C (UC)", goal = 20 },
    [3021] = { name = "Vanquish Vermin C (UC)", goal = 20 },
    [3022] = { name = "Vanquish Birds with Physical Damage C (UC)", goal = 20 },
    [3023] = { name = "Vanquish Lizards with Magic C (UC)", goal = 20 },
    [3024] = { name = "Total Successful Goldsmithing Syntheses C (UC)", goal = 10 },
    [3026] = { name = "Total Suc. Harvesting Attempts C (UC)", goal = 10 },
    [3027] = { name = "Unity Communique D (UC)", goal = 1 },
    [3029] = { name = "Vanquish Multiple Enemies D (UC)", goal = 20 },
    [3030] = { name = "Vanquish Beasts D (UC)", goal = 20 },
    [3031] = { name = "Vanquish Aquans with Physical Damage D (UC)", goal = 20 },
    [3032] = { name = "Vanquish Amorphs with Magic D (UC)", goal = 20 },
    [3033] = { name = "Total Successful Cloth Syntheses D (UC)", goal = 10 },
    [3034] = { name = "Total Successful Bone Syntheses D (UC)", goal = 10 },
    [3035] = { name = "Total Suc. Mining Attempts D (UC)", goal = 10 },
    [3036] = { name = "Unity Communique E (UC)", goal = 1 },
    [3038] = { name = "Vanquish Multiple Enemies E (UC)", goal = 20 },
    [3039] = { name = "Vanquish Plantoids E (UC)", goal = 20 },
    [3040] = { name = "Vanquish Arcana with Physical Damage E (UC)", goal = 20 },
    [3041] = { name = "Vanquish Undead with Magic E (UC)", goal = 20 },
    [3042] = { name = "Total Successful Cooking Syntheses E (UC)", goal = 10 },
    [3044] = { name = "Total Suc. Logging Attempts E (UC)", goal = 10 },
    [3045] = { name = "Unity Communique F (UC)", goal = 1 },
    [3046] = { name = "Level Sync to Vanquish Enemies F (UC)", goal = 20 },
    [3047] = { name = "Vanquish Multiple Enemies F (UC)", goal = 20 },
    [3048] = { name = "Vanquish Lizards F (UC)", goal = 20 },
    [3049] = { name = "Vanquish Vermin with Physical Damage F (UC)", goal = 20 },
    [3050] = { name = "Vanquish Birds with Magic F (UC)", goal = 20 },
    [3051] = { name = "Total Successful Alchemy Syntheses F (UC)", goal = 10 },
    [3053] = { name = "Total Suc. Harvesting Attempts F (UC)", goal = 10 },
    [3367] = { name = "Signet, brb (W)", goal = 1 },
    [3488] = { name = "Club Weapon Skills (UC)", goal = 30 },
    [3489] = { name = "Conflict: Rala Waterways (UC)", goal = 10 },
    [3490] = { name = "Vanquish Rabbits (UC)", goal = 10 },
    [3491] = { name = "Subjugation: Rambukk (UC)", goal = 1 },
    [3492] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3493] = { name = "Spoils - Bat Fangs (UC)", goal = 5 },
    [3494] = { name = "Conflict: La Theine Plateau (UC)", goal = 10 },
    [3495] = { name = "Vanquish Bats (UC)", goal = 10 },
    [3496] = { name = "Subjugation: Tumbling Truffle (UC)", goal = 1 },
    [3498] = { name = "Staff Weapon Skills (UC)", goal = 30 },
    [3499] = { name = "Conflict: Eldieme Necropolis (UC)", goal = 10 },
    [3500] = { name = "Vanquish Treants (UC)", goal = 10 },
    [3501] = { name = "Subjugation: Duke Decapod (UC)", goal = 1 },
    [3502] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3503] = { name = "Spoils - Bomb Ash (UC)", goal = 5 },
    [3504] = { name = "Conflict: Davoi (UC)", goal = 10 },
    [3505] = { name = "Vanquish Bombs (UC)", goal = 10 },
    [3506] = { name = "Subjugation: Poisonhand Gnadgad (UC)", goal = 1 },
    [3507] = { name = "Magic Bursts (UC)", goal = 10 },
    [3508] = { name = "Great Katana Weapon Skills (UC)", goal = 30 },
    [3509] = { name = "Conflict: North Gustaberg (UC)", goal = 10 },
    [3510] = { name = "Vanquish Worms (UC)", goal = 10 },
    [3511] = { name = "Subjugation: Stinging Sophie (UC)", goal = 1 },
    [3512] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3513] = { name = "Spoils - Cockatrice Meat (UC)", goal = 5 },
    [3514] = { name = "Conflict: Yahse Hunting Grounds (UC)", goal = 10 },
    [3515] = { name = "Vanquish Cockatrices (UC)", goal = 10 },
    [3516] = { name = "Subjugation: Tococo (UC)", goal = 1 },
    [3518] = { name = "Archery Weapon Skills (UC)", goal = 30 },
    [3519] = { name = "Conflict: Crawlers\' Nest (UC)", goal = 10 },
    [3520] = { name = "Vanquish Lizards (UC)", goal = 10 },
    [3521] = { name = "Subjugation: Aqrabuamelu (UC)", goal = 1 },
    [3522] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3523] = { name = "Spoils - Land Crab Meat (UC)", goal = 5 },
    [3524] = { name = "Conflict: Beadeaux (UC)", goal = 10 },
    [3525] = { name = "Vanquish Crabs (UC)", goal = 10 },
    [3526] = { name = "Subjugation: Ge\'Dha Evileye (UC)", goal = 1 },
    [3527] = { name = "Magic Bursts (UC)", goal = 5 },
    [3528] = { name = "Axe Weapon Skills (UC)", goal = 30 },
    [3529] = { name = "Conflict: South Gustaberg (UC)", goal = 10 },
    [3530] = { name = "Vanquish Sea Monks (UC)", goal = 10 },
    [3531] = { name = "Subjugation: Leaping Lizzy (UC)", goal = 1 },
    [3532] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3533] = { name = "Spoils - Sleepshroom (UC)", goal = 5 },
    [3534] = { name = "Conflict: Pashhow Marshlands (UC)", goal = 10 },
    [3535] = { name = "Vanquish Funguars (UC)", goal = 10 },
    [3536] = { name = "Subjugation: Bloodpool Vorax (UC)", goal = 1 },
    [3538] = { name = "Great Axe Weapon Skills (UC)", goal = 30 },
    [3539] = { name = "Conflict: Ceizak Battlegrounds (UC)", goal = 10 },
    [3540] = { name = "Vanquish Flies (UC)", goal = 10 },
    [3541] = { name = "Subjugation: Be\'Hya Hundredwall (UC)", goal = 1 },
    [3542] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3543] = { name = "Spoils - Raptor Skin (UC)", goal = 5 },
    [3544] = { name = "Conflict: Beaucedine Glacier (UC)", goal = 10 },
    [3545] = { name = "Vanquish Raptors (UC)", goal = 10 },
    [3546] = { name = "Subjugation: Gargantua (UC)", goal = 1 },
    [3547] = { name = "Magic Bursts (UC)", goal = 5 },
    [3548] = { name = "Club Weapon Skills (UC)", goal = 30 },
    [3549] = { name = "Conflict: West Sarutabaruta (UC)", goal = 10 },
    [3550] = { name = "Vanquish Bees (UC)", goal = 10 },
    [3551] = { name = "Subjugation: Tom Tit Tat (UC)", goal = 1 },
    [3552] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3553] = { name = "Spoils - Silk Thread (UC)", goal = 5 },
    [3554] = { name = "Conflict: Buburimu Peninsula (UC)", goal = 10 },
    [3555] = { name = "Vanquish Crawlers (UC)", goal = 10 },
    [3556] = { name = "Subjugation: Buburimboo (UC)", goal = 1 },
    [3558] = { name = "Staff Weapon Skills (UC)", goal = 30 },
    [3559] = { name = "Conflict: Castle Oztroja (UC)", goal = 10 },
    [3560] = { name = "Vanquish Ghosts (UC)", goal = 10 },
    [3561] = { name = "Subjugation: Mee Deggi the Punisher (UC)", goal = 1 },
    [3562] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3563] = { name = "Spoils - Saruta Cotton (UC)", goal = 5 },
    [3564] = { name = "Conflict: Foret de Hennetiel (UC)", goal = 10 },
    [3565] = { name = "Vanquish Mandragoras (UC)", goal = 10 },
    [3566] = { name = "Subjugation: Juu Duzu the Whirlwind (UC)", goal = 1 },
    [3567] = { name = "Magic Bursts (UC)", goal = 10 },
    [3568] = { name = "Hand-to-Hand Weapon Skills (UC)", goal = 30 },
    [3569] = { name = "Conflict: Yorcia Weald (UC)", goal = 10 },
    [3570] = { name = "Vanquish Leeches (UC)", goal = 10 },
    [3571] = { name = "Subjugation: Canal Moocher (UC)", goal = 1 },
    [3572] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3573] = { name = "Spoils - Spider Web (UC)", goal = 5 },
    [3574] = { name = "Conflict: Rolanberry Fields (UC)", goal = 10 },
    [3575] = { name = "Vanquish Spiders (UC)", goal = 10 },
    [3576] = { name = "Subjugation: Eldritch Edge (UC)", goal = 1 },
    [3578] = { name = "Great Sword Weapon Skills (UC)", goal = 30 },
    [3579] = { name = "Conflict: Meriphataud Mountains (UC)", goal = 10 },
    [3580] = { name = "Vanquish Wyverns (UC)", goal = 10 },
    [3581] = { name = "Subjugation: Patripatan (UC)", goal = 1 },
    [3582] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3583] = { name = "Spoils - Hecteyes Eye (UC)", goal = 5 },
    [3584] = { name = "Conflict: Sauromugue Champaign (UC)", goal = 10 },
    [3585] = { name = "Vanquish Hecteyes (UC)", goal = 10 },
    [3586] = { name = "Subjugation: Bashe (UC)", goal = 1 },
    [3587] = { name = "Magic Bursts (UC)", goal = 10 },
    [3588] = { name = "Dagger Weapon Skills (UC)", goal = 30 },
    [3589] = { name = "Conflict: Sanctuary of Zi\'Tah (UC)", goal = 10 },
    [3590] = { name = "Vanquish Hounds (UC)", goal = 10 },
    [3591] = { name = "Subjugation: Bastet (UC)", goal = 1 },
    [3592] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3593] = { name = "Spoils - Doll Shard (UC)", goal = 5 },
    [3594] = { name = "Conflict: Morimar Basalt Fields (UC)", goal = 10 },
    [3595] = { name = "Vanquish Dolls (UC)", goal = 10 },
    [3596] = { name = "Subjugation: Nocuous Weapon (UC)", goal = 1 },
    [3598] = { name = "Marksmanship Weapon Skills (UC)", goal = 30 },
    [3599] = { name = "Conflict: Boyahda Tree (UC)", goal = 10 },
    [3600] = { name = "Vanquish Slimes (UC)", goal = 10 },
    [3601] = { name = "Subjugation: Aquarius (UC)", goal = 1 },
    [3602] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3603] = { name = "Spoils - Bird Egg (UC)", goal = 5 },
    [3604] = { name = "Conflict: Western Altepa Desert (UC)", goal = 10 },
    [3605] = { name = "Vanquish Crow-Type Birds (UC)", goal = 10 },
    [3606] = { name = "Subjugation: Cactuar Cantautor (UC)", goal = 1 },
    [3607] = { name = "Magic Bursts (UC)", goal = 10 },
    [3608] = { name = "Dagger Weapon Skills (UC)", goal = 30 },
    [3609] = { name = "Conflict: Yuhtunga Jungle (UC)", goal = 10 },
    [3610] = { name = "Vanquish Sheep (UC)", goal = 10 },
    [3611] = { name = "Subjugation: Mischievous Micholas (UC)", goal = 1 },
    [3612] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3613] = { name = "Spoils - Scorpion Claw (UC)", goal = 5 },
    [3614] = { name = "Conflict: East Sarutabaruta (UC)", goal = 10 },
    [3615] = { name = "Vanquish Scorpions (UC)", goal = 10 },
    [3616] = { name = "Subjugation: Sharp-Eared Ropipi (UC)", goal = 1 },
    [3618] = { name = "Archery Weapon Skills (UC)", goal = 30 },
    [3619] = { name = "Conflict: Marjami Ravine (UC)", goal = 10 },
    [3620] = { name = "Vanquish Opo-Opos (UC)", goal = 10 },
    [3621] = { name = "Subjugation: Ah Puch (UC)", goal = 1 },
    [3622] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3623] = { name = "Spoils - Black Tiger Fang (UC)", goal = 5 },
    [3624] = { name = "Conflict: Sea Serpent Grotto (UC)", goal = 10 },
    [3625] = { name = "Vanquish Tigers (UC)", goal = 10 },
    [3626] = { name = "Subjugation: Fyuu the Seabellow (UC)", goal = 1 },
    [3627] = { name = "Magic Bursts (UC)", goal = 10 },
    [3628] = { name = "Club Weapon Skills (UC)", goal = 30 },
    [3629] = { name = "Conflict: Bhaflau Thickets (UC)", goal = 10 },
    [3630] = { name = "Vanquish Evil Weapons (UC)", goal = 10 },
    [3631] = { name = "Subjugation: Emergent Elm (UC)", goal = 1 },
    [3632] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3633] = { name = "Spoils - Puk Wing (UC)", goal = 5 },
    [3634] = { name = "Conflict: West Ronfaure (UC)", goal = 10 },
    [3635] = { name = "Vanquish Puks (UC)", goal = 10 },
    [3636] = { name = "Subjugation: Fungus Beetle (UC)", goal = 1 },
    [3638] = { name = "Staff Weapon Skills (UC)", goal = 30 },
    [3639] = { name = "Conflict: Wajaom Woodlands (UC)", goal = 10 },
    [3640] = { name = "Vanquish Elementals (UC)", goal = 10 },
    [3641] = { name = "Subjugation: Jaded Jody (UC)", goal = 1 },
    [3642] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3643] = { name = "Spoils - Dhalmel Meat (UC)", goal = 5 },
    [3644] = { name = "Conflict: Kamihr Drifts (UC)", goal = 10 },
    [3645] = { name = "Vanquish Dhalmel (UC)", goal = 10 },
    [3646] = { name = "Subjugation: Trembler Tabitha (UC)", goal = 1 },
    [3647] = { name = "Magic Bursts (UC)", goal = 5 },
    [3648] = { name = "Polearm Weapon Skills (UC)", goal = 30 },
    [3649] = { name = "Conflict: Cirdas Caverns (UC)", goal = 10 },
    [3650] = { name = "Vanquish Pugils (UC)", goal = 10 },
    [3651] = { name = "Subjugation: Hovering Hotpot (UC)", goal = 1 },
    [3652] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3653] = { name = "Spoils - Beetle Shell (UC)", goal = 5 },
    [3654] = { name = "Conflict: East Ronfaure (UC)", goal = 10 },
    [3655] = { name = "Vanquish Beetles (UC)", goal = 10 },
    [3656] = { name = "Subjugation: Bigmouth Billy (UC)", goal = 1 },
    [3658] = { name = "Sword Weapon Skills (UC)", goal = 30 },
    [3659] = { name = "Conflict: Xarcabard (UC)", goal = 10 },
    [3660] = { name = "Vanquish Goobbues (UC)", goal = 10 },
    [3661] = { name = "Subjugation: Barbaric Weapon (UC)", goal = 1 },
    [3662] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3663] = { name = "Spoils - Bone Chip (UC)", goal = 5 },
    [3664] = { name = "Conflict: Woh Gates (UC)", goal = 10 },
    [3665] = { name = "Vanquish Skeletons (UC)", goal = 10 },
    [3666] = { name = "Subjugation: Hyakume (UC)", goal = 1 },
    [3667] = { name = "Magic Bursts (UC)", goal = 10 },
    [3668] = { name = "Club Weapon Skills (UC)", goal = 30 },
    [3669] = { name = "Conflict: Giddeus (UC)", goal = 10 },
    [3670] = { name = "Vanquish Efts (UC)", goal = 10 },
    [3671] = { name = "Subjugation: Herbage Hunter (UC)", goal = 1 },
    [3672] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3673] = { name = "Spoils - Rotten Meat (UC)", goal = 5 },
    [3674] = { name = "Conflict: Moh Gates (UC)", goal = 10 },
    [3675] = { name = "Vanquish Antica (UC)", goal = 10 },
    [3676] = { name = "Subjugation: Antican Praefectus (UC)", goal = 1 },
    [3678] = { name = "Staff Weapon Skills (UC)", goal = 30 },
    [3679] = { name = "Conflict: Toraimarai Canal (UC)", goal = 10 },
    [3680] = { name = "Vanquish Coeurls (UC)", goal = 10 },
    [3681] = { name = "Subjugation: Ose (UC)", goal = 1 },
    [3682] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3683] = { name = "Spoils - Dullahan Armor (UC)", goal = 5 },
    [3684] = { name = "Conflict: Outer Ra\'Kaznar (UC)", goal = 10 },
    [3685] = { name = "Vanquish Dullahan (UC)", goal = 10 },
    [3686] = { name = "Subjugation: Capricious Cassie (UC)", goal = 1 },
    [3687] = { name = "Magic Bursts (UC)", goal = 10 },
    [3688] = { name = "Club Weapon Skills (UC)", goal = 30 },
    [3689] = { name = "Conflict: Sih Gates (UC)", goal = 10 },
    [3690] = { name = "Vanquish Acuex (UC)", goal = 10 },
    [3691] = { name = "Subjugation: Intulo (UC)", goal = 1 },
    [3692] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3693] = { name = "Spoils - Demon Horn (UC)", goal = 5 },
    [3694] = { name = "Conflict: Konschtat Highlands (UC)", goal = 10 },
    [3695] = { name = "Vanquish Demons (UC)", goal = 10 },
    [3696] = { name = "Subjugation: Marquis Naberius (UC)", goal = 1 },
    [3698] = { name = "Staff Weapon Skills (UC)", goal = 30 },
    [3699] = { name = "Conflict: Dho Gates (UC)", goal = 10 },
    [3700] = { name = "Vanquish Velkk (UC)", goal = 10 },
    [3701] = { name = "Subjugation: Dune Widow (UC)", goal = 1 },
    [3702] = { name = "Heal Unity Allies (UC)", goal = 30 },
    [3703] = { name = "Spoils - Twitherym Wing (UC)", goal = 5 },
    [3704] = { name = "Conflict: Qufim Island (UC)", goal = 10 },
    [3705] = { name = "Vanquish Twitherym (UC)", goal = 10 },
    [3706] = { name = "Subjugation: Atkorkamuy (UC)", goal = 1 },
    [3707] = { name = "Magic Bursts (UC)", goal = 10 },
    [4008] = { name = "Vanquish Aquans", goal = 20 },
    [4009] = { name = "Vanquish Beasts", goal = 20 },
    [4010] = { name = "Vanquish Plantoids", goal = 20 },
    [4011] = { name = "Vanquish Lizards", goal = 20 },
    [4012] = { name = "Vanquish Vermin", goal = 20 },
    [4013] = { name = "Gain Experience", goal = 5000 },
    [4014] = { name = "Spoils (Seals)", goal = 3 },
    [4015] = { name = "Vanquish Birds", goal = 20 },
    [4016] = { name = "Vanquish Amorphs", goal = 20 },
    [4017] = { name = "Vanquish Undead", goal = 20 },
    [4018] = { name = "Vanquish Arcana", goal = 20 },
    [4019] = { name = "Crack Treasure Caskets (Triggered from caskets.lua)", goal = 10 },
    [4020] = { name = "Physical Damage Kills", goal = 20 },
    [4021] = { name = "Magic Damage Kills", goal = 20 },
    [4082] = { name = "Vanquish Multiple Enemies (D)", goal = 30 },
    [4083] = { name = "Buff Allies (D)", goal = 20 },
    [4084] = { name = "Heal for 500+ HP (D)", goal = 30 },
    [4085] = { name = "10 RoE Objectives Complete (All for One requirement)", goal = 1 },
}